OpenSSL/Digest.hs: drop MD2 support
Trying to link hopenssl results in the following error, if the openssl
version is >=1.0.0:

/usr/lib64/hopenssl-1.4/ghc-6.12.3/libHShopenssl-1.4.a(Digest.o): In function `s2GN_info':
(.text+0xdc0): undefined reference to `EVP_md2'
/usr/lib64/hopenssl-1.4/ghc-6.12.3/libHShopenssl-1.4.a(Digest.o): In function `s2Mx_info':
(.text+0x14cb): undefined reference to `EVP_md2'
collect2: ld returned 1 exit status

As it turns out the Configure script of openssl disables MD2 since
version 1.0.0. As a result disable the MD2 algorithm in hopenssl.